name: "Urban Delivery Default"
description: "Default scenario for an urban delivery truck comparison, post-refactor."
analysis_years: 15 # e.g., 2025 to 2039 inclusive

# Economic
discount_rate_real: 0.05 # Example real discount rate

# Operational
annual_mileage: 40000 # km/year
electric_maintenance_cost_per_km: 0.06 # Added back - Required by Scenario model
diesel_maintenance_cost_per_km: 0.12 # Added back - Required by Scenario model
# electric_maintenance_cost_per_km: 0.06 # Removed - Moved back into EV block
# diesel_maintenance_cost_per_km: 0.12 # Removed - Moved back into Diesel block
annual_registration_cost: 0 # AUD/year (base year) - Added top-level field (Placeholder, review if needed)

# Electric Vehicle
# Using nested structure based on tco_model.vehicles.ElectricVehicle
electric_vehicle:
  name: "Urban Delivery EV (Default)"
  purchase_price: 350000 # AUD
  residual_value_percent: 0.15 # Proportion of purchase price after analysis_years
  energy_consumption_kwh_per_km: 0.9 # kWh/km - Renamed from energy_consumption
  maintenance_cost_per_km: 0.06 # AUD/km (base year) - Moved back into block
  insurance_cost_percent: 0.02 # % of purchase price (base year)
  registration_cost: 1500 # AUD/year (base year) - Kept for now, check if needed alongside top-level
  battery_capacity_kwh: 300 # kWh
  battery_replacement_cost_per_kwh: 150 # AUD/kWh - Added missing field (Placeholder value)
  battery_cycle_life: 2500 # Cycles
  battery_depth_of_discharge: 0.85 # DoD
  charging_efficiency: 0.92 # Grid-to-battery efficiency

# Diesel Vehicle
# Using nested structure based on tco_model.vehicles.DieselVehicle
diesel_vehicle:
  name: "Urban Delivery Diesel (Default)"
  purchase_price: 200000 # AUD
  residual_value_percent: 0.12 # Proportion of purchase price after analysis_years
  fuel_consumption_l_per_100km: 30.0 # L/100km - Renamed from energy_consumption & converted from 0.3 L/km
  maintenance_cost_per_km: 0.12 # AUD/km (base year) - Moved back into block
  insurance_cost_percent: 0.025 # % of purchase price (base year)
  registration_cost: 2500 # AUD/year (base year) - Kept for now, check if needed alongside top-level
  co2_emission_factor: 2.68 # kg CO2e/L

# Infrastructure (EV)
infrastructure_cost: 75000 # AUD (charger + installation)
infrastructure_maintenance_percent: 0.01 # Annual % of upfront cost

# Base Prices/Rates (Year 0 / Initial)
electricity_price: 0.20 # AUD/kWh
diesel_price: 1.80 # AUD/L
carbon_tax_rate: 30.0 # AUD/tonne CO2e
road_user_charge: 0.0 # AUD/km (Example: Assuming none initially)

# Annual Increase Rates
electricity_price_increase: 0.02 # 2% annual increase
diesel_price_increase: 0.015 # 1.5% annual increase
carbon_tax_increase_rate: 0.05 # 5% annual increase
road_user_charge_increase_rate: 0.0 # 0% increase
maintenance_increase_rate: 0.01 # 1% annual increase
insurance_increase_rate: 0.01 # 1% annual increase
registration_increase_rate: 0.01 # 1% annual increase

# Flags / Options
include_carbon_tax: true
include_road_user_charge: false # Set to false as rate is 0

# Battery Replacement (EV)
battery_degradation_rate: 0.02 # 2% annual capacity loss
battery_replacement_threshold: 0.70 # Replace if capacity drops below 70%
force_battery_replacement_year: null # Let degradation trigger it (or set a year, e.g., 8)
