name: "Urban Delivery Default - Refactored"
description: "Default scenario for an urban delivery truck comparison, refactored structure."
analysis_period_years: 15
analysis_start_year: 2025 # Added default

# --- Economic Parameters ---
economic_parameters:
  discount_rate_percent_real: 5.0 # Scaled (0.05 -> 5.0)
  inflation_rate_percent: 2.5 # Added default

# --- Operational Parameters ---
operational_parameters:
  annual_mileage_km: 40000 # Renamed

# --- Financing Options --- # Added default structure
financing_options:
  financing_method: loan
  down_payment_percent: 20.0
  loan_term_years: 5
  loan_interest_rate_percent: 6.5 # Default

# --- Vehicle Definitions ---
electric_vehicle:
  name: "Urban Delivery EV (Default)"
  vehicle_type: rigid # Assumed type
  base_purchase_price_aud: 350000 # Renamed
  lifespan_years: 15 # Explicit lifespan
  residual_value_percent_projections: # Renamed and structured
    15: 0.15 # Used residual_value_percent at analysis_years
  base_registration_cost_aud: 1500 # Renamed (used vehicle-specific registration_cost)
  # purchase_price_annual_decrease_rate_real: 0.0 # Add if needed
  # Battery Details
  battery_capacity_kwh: 300
  energy_consumption_kwh_per_km: 0.9
  battery_warranty_years: 8 # Added default
  # Added placeholder projections, original file used battery_replacement_cost_per_kwh inside EV block
  battery_pack_cost_aud_per_kwh_projections:
    2025: 150 # Used EV.battery_replacement_cost_per_kwh for initial year
    2030: 100 # Placeholder
    2035: 75 # Placeholder
    2040: 60 # Placeholder
  battery_cycle_life: 2500
  battery_depth_of_discharge_percent: 85.0 # Renamed & Scaled (0.85 -> 85.0)
  charging_efficiency_percent: 92.0 # Renamed & Scaled (0.92 -> 92.0)

diesel_vehicle:
  name: "Urban Delivery Diesel (Default)"
  vehicle_type: rigid # Assumed type
  base_purchase_price_aud: 200000 # Renamed
  lifespan_years: 15 # Explicit lifespan
  residual_value_percent_projections: # Renamed and structured
    15: 0.12 # Used residual_value_percent at analysis_years
  base_registration_cost_aud: 2500 # Renamed (used vehicle-specific registration_cost)
  # Fuel Details
  fuel_consumption_l_per_100km: 30.0
  co2_emission_factor_kg_per_l: 2.68 # Renamed

# --- Infrastructure Costs ---
infrastructure_costs:
  selected_charger_cost_aud: 75000 # Renamed (used infrastructure_cost)
  selected_installation_cost_aud: 0 # Renamed (set to 0, adjust as needed)
  charger_maintenance_annual_rate_percent: 1.0 # Renamed & Scaled (0.01 -> 1.0)
  charger_lifespan_years: 10 # Renamed (Added default)

# --- Price Projections & Selections ---
# NOTE: Original file used base price + increase rate. New model expects projections.
# Created minimal projections using base price for start year only.
# User MUST update these projections for a realistic scenario.
electricity_price_projections:
  selected_scenario_name: constant_base
  scenarios:
    - name: constant_base
      prices:
        2025: { price_aud_per_kwh_or_range: 0.20 }

diesel_price_projections:
  selected_scenario_name: constant_base
  scenarios:
    - name: constant_base
      data: { price_aud_per_l_or_projection: 1.80 }

# --- Detailed Maintenance Costs ---
# NOTE: Original file used cost_per_km. New model expects detailed structure.
# Created structure based on assumed vehicle type and cost_per_km.
maintenance_costs_detailed:
  rigid_bet:
    cost_aud_per_km: 0.06 # Used electric_maintenance_cost_per_km
    # Add other fields if available/needed
  rigid_diesel:
    cost_aud_per_km: 0.12 # Used diesel_maintenance_cost_per_km
    # Add other fields if available/needed

# --- Insurance and Registration Costs ---
# NOTE: Original file used insurance_cost_percent per vehicle.
# Moved into structured format, using vehicle-specific registration cost.
insurance_registration_costs:
  electric:
    base_annual_cost_aud: 1500 # Used vehicle-specific registration_cost
    cost_type: percentage_of_value # Based on original insurance_cost_percent
    annual_rate_percent_of_value: 2.0 # Used electric insurance_cost_percent, Scaled (0.02->2.0)
  diesel:
    base_annual_cost_aud: 2500 # Used vehicle-specific registration_cost
    cost_type: percentage_of_value # Based on original insurance_cost_percent
    annual_rate_percent_of_value: 2.5 # Used diesel insurance_cost_percent, Scaled (0.025->2.5)

# --- Carbon Tax Configuration ---
carbon_tax_config:
  include_carbon_tax: true # Renamed
  initial_rate_aud_per_tonne_co2e: 30.0 # Renamed
  annual_increase_rate_percent: 5.0 # Renamed & Scaled (0.05 -> 5.0)

# --- Road User Charge Configuration ---
road_user_charge_config:
  include_road_user_charge: false # Renamed
  initial_charge_aud_per_km: 0.0 # Renamed
  annual_increase_rate_percent: 0.0 # Renamed & Scaled (0.0 -> 0.0)

# --- General Cost Increase Rates ---
general_cost_increase_rates:
  maintenance_annual_increase_rate_percent: 1.0 # Renamed & Scaled (0.01 -> 1.0)
  insurance_annual_increase_rate_percent: 1.0 # Renamed & Scaled (0.01 -> 1.0)
  registration_annual_increase_rate_percent: 1.0 # Renamed & Scaled (0.01 -> 1.0)

# --- Battery Replacement Configuration ---
battery_replacement_config:
  enable_battery_replacement: true # Added default
  annual_degradation_rate_percent: 2.0 # Renamed & Scaled (0.02 -> 2.0)
  replacement_threshold_fraction: 0.70 # Renamed (Scale unchanged)
  force_replacement_year_index: null # Renamed
