# config/defaults/economic.yaml
# Default economic parameters for the TCO model

general:
  current_year: 2023
  currency: "AUD"

economic:
  discount_rate: 7.0  # %
  inflation_rate: 2.5 # %
  cost_increase_rate: 0.0 # % annual real increase for various costs

loan:
  interest_rate: 7.0  # %
  down_payment_pct: 20.0 # %

taxes_charges:
  carbon_tax_rate: 30.0 # AUD/tonne CO2e
  road_user_charge: 0.0  # AUD/km

analysis:
  years: 15
  annual_mileage: 40000.0 # km

registration_insurance:
  annual_registration_cost: 5000.0 # AUD

# Note: Payment frequency and related logic might be better handled in code
# or a different config section if it drives logic rather than just being data.
# payment_frequency: "monthly" 
# payments_per_year: 
#   monthly: 12
#   quarterly: 4
#   annually: 1 